// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dpu_server;

namespace dpu_server.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200321151739_test2")]
    partial class test2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("dpu_server.Models.Heatmap", b =>
                {
                    b.Property<int>("HeatmapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("HeatmapID");

                    b.ToTable("Heatmaps");
                });

            modelBuilder.Entity("dpu_server.Models.Referencepoint", b =>
                {
                    b.Property<int>("ReferencepointID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("HeatmapId")
                        .HasColumnType("int");

                    b.Property<int>("RSSI1")
                        .HasColumnType("int");

                    b.Property<int>("RSSI2")
                        .HasColumnType("int");

                    b.Property<int>("RSSI3")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("ReferencepointID");

                    b.HasIndex("HeatmapId")
                        .IsUnique();

                    b.ToTable("Referencepoints");
                });

            modelBuilder.Entity("dpu_server.Models.Referencepoint", b =>
                {
                    b.HasOne("dpu_server.Models.Heatmap", "Heatmap")
                        .WithOne("Referencepoint")
                        .HasForeignKey("dpu_server.Models.Referencepoint", "HeatmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
