// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dpu_server;

namespace dpu_server.Migrations
{
    [DbContext(typeof(FruitFlyContext))]
    [Migration("20200507175143_othertestdata")]
    partial class othertestdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("dpu_server.Models.Heatmap", b =>
                {
                    b.Property<int>("HeatmapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ReferencepointId")
                        .HasColumnType("int");

                    b.Property<int?>("ReferencepointId1")
                        .HasColumnType("int");

                    b.HasKey("HeatmapID");

                    b.HasIndex("ReferencepointId");

                    b.HasIndex("ReferencepointId1")
                        .IsUnique()
                        .HasFilter("[ReferencepointId1] IS NOT NULL");

                    b.ToTable("Heatmaps");
                });

            modelBuilder.Entity("dpu_server.Models.Referencepoint", b =>
                {
                    b.Property<int>("ReferencepointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("RSSI1")
                        .HasColumnType("int");

                    b.Property<int>("RSSI2")
                        .HasColumnType("int");

                    b.Property<int>("RSSI3")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("ReferencepointId");

                    b.ToTable("Referencepoints");

                    b.HasData(
                        new
                        {
                            ReferencepointId = 11,
                            Category = 7,
                            RSSI1 = 63,
                            RSSI2 = 63,
                            RSSI3 = 63,
                            X = 1,
                            Y = 1
                        },
                        new
                        {
                            ReferencepointId = 12,
                            Category = 6,
                            RSSI1 = 75,
                            RSSI2 = 51,
                            RSSI3 = 75,
                            X = 1,
                            Y = 2
                        },
                        new
                        {
                            ReferencepointId = 13,
                            Category = 6,
                            RSSI1 = 87,
                            RSSI2 = 39,
                            RSSI3 = 87,
                            X = 1,
                            Y = 3
                        },
                        new
                        {
                            ReferencepointId = 14,
                            Category = 3,
                            RSSI1 = 99,
                            RSSI2 = 27,
                            RSSI3 = 99,
                            X = 1,
                            Y = 4
                        },
                        new
                        {
                            ReferencepointId = 15,
                            Category = 6,
                            RSSI1 = 111,
                            RSSI2 = 15,
                            RSSI3 = 111,
                            X = 1,
                            Y = 5
                        },
                        new
                        {
                            ReferencepointId = 16,
                            Category = 1,
                            RSSI1 = 123,
                            RSSI2 = 3,
                            RSSI3 = 123,
                            X = 1,
                            Y = 6
                        },
                        new
                        {
                            ReferencepointId = 17,
                            Category = 5,
                            RSSI1 = 135,
                            RSSI2 = -9,
                            RSSI3 = 135,
                            X = 1,
                            Y = 7
                        },
                        new
                        {
                            ReferencepointId = 18,
                            Category = 8,
                            RSSI1 = 147,
                            RSSI2 = -21,
                            RSSI3 = 147,
                            X = 1,
                            Y = 8
                        },
                        new
                        {
                            ReferencepointId = 19,
                            Category = 5,
                            RSSI1 = 159,
                            RSSI2 = -33,
                            RSSI3 = 159,
                            X = 1,
                            Y = 9
                        },
                        new
                        {
                            ReferencepointId = 21,
                            Category = 7,
                            RSSI1 = 75,
                            RSSI2 = 51,
                            RSSI3 = 51,
                            X = 2,
                            Y = 1
                        },
                        new
                        {
                            ReferencepointId = 22,
                            Category = 8,
                            RSSI1 = 87,
                            RSSI2 = 39,
                            RSSI3 = 63,
                            X = 2,
                            Y = 2
                        },
                        new
                        {
                            ReferencepointId = 23,
                            Category = 9,
                            RSSI1 = 99,
                            RSSI2 = 27,
                            RSSI3 = 75,
                            X = 2,
                            Y = 3
                        },
                        new
                        {
                            ReferencepointId = 24,
                            Category = 3,
                            RSSI1 = 111,
                            RSSI2 = 15,
                            RSSI3 = 87,
                            X = 2,
                            Y = 4
                        },
                        new
                        {
                            ReferencepointId = 25,
                            Category = 9,
                            RSSI1 = 123,
                            RSSI2 = 3,
                            RSSI3 = 99,
                            X = 2,
                            Y = 5
                        },
                        new
                        {
                            ReferencepointId = 26,
                            Category = 7,
                            RSSI1 = 135,
                            RSSI2 = -9,
                            RSSI3 = 111,
                            X = 2,
                            Y = 6
                        },
                        new
                        {
                            ReferencepointId = 27,
                            Category = 5,
                            RSSI1 = 147,
                            RSSI2 = -21,
                            RSSI3 = 123,
                            X = 2,
                            Y = 7
                        },
                        new
                        {
                            ReferencepointId = 28,
                            Category = 5,
                            RSSI1 = 159,
                            RSSI2 = -33,
                            RSSI3 = 135,
                            X = 2,
                            Y = 8
                        },
                        new
                        {
                            ReferencepointId = 29,
                            Category = 5,
                            RSSI1 = 171,
                            RSSI2 = -45,
                            RSSI3 = 147,
                            X = 2,
                            Y = 9
                        },
                        new
                        {
                            ReferencepointId = 31,
                            Category = 9,
                            RSSI1 = 87,
                            RSSI2 = 39,
                            RSSI3 = 39,
                            X = 3,
                            Y = 1
                        },
                        new
                        {
                            ReferencepointId = 32,
                            Category = 1,
                            RSSI1 = 99,
                            RSSI2 = 27,
                            RSSI3 = 51,
                            X = 3,
                            Y = 2
                        },
                        new
                        {
                            ReferencepointId = 33,
                            Category = 1,
                            RSSI1 = 111,
                            RSSI2 = 15,
                            RSSI3 = 63,
                            X = 3,
                            Y = 3
                        },
                        new
                        {
                            ReferencepointId = 34,
                            Category = 5,
                            RSSI1 = 123,
                            RSSI2 = 3,
                            RSSI3 = 75,
                            X = 3,
                            Y = 4
                        },
                        new
                        {
                            ReferencepointId = 35,
                            Category = 3,
                            RSSI1 = 135,
                            RSSI2 = -9,
                            RSSI3 = 87,
                            X = 3,
                            Y = 5
                        },
                        new
                        {
                            ReferencepointId = 36,
                            Category = 3,
                            RSSI1 = 147,
                            RSSI2 = -21,
                            RSSI3 = 99,
                            X = 3,
                            Y = 6
                        },
                        new
                        {
                            ReferencepointId = 37,
                            Category = 7,
                            RSSI1 = 159,
                            RSSI2 = -33,
                            RSSI3 = 111,
                            X = 3,
                            Y = 7
                        },
                        new
                        {
                            ReferencepointId = 38,
                            Category = 9,
                            RSSI1 = 171,
                            RSSI2 = -45,
                            RSSI3 = 123,
                            X = 3,
                            Y = 8
                        },
                        new
                        {
                            ReferencepointId = 39,
                            Category = 1,
                            RSSI1 = 183,
                            RSSI2 = -57,
                            RSSI3 = 135,
                            X = 3,
                            Y = 9
                        },
                        new
                        {
                            ReferencepointId = 41,
                            Category = 2,
                            RSSI1 = 99,
                            RSSI2 = 27,
                            RSSI3 = 27,
                            X = 4,
                            Y = 1
                        },
                        new
                        {
                            ReferencepointId = 42,
                            Category = 2,
                            RSSI1 = 111,
                            RSSI2 = 15,
                            RSSI3 = 39,
                            X = 4,
                            Y = 2
                        },
                        new
                        {
                            ReferencepointId = 43,
                            Category = 6,
                            RSSI1 = 123,
                            RSSI2 = 3,
                            RSSI3 = 51,
                            X = 4,
                            Y = 3
                        },
                        new
                        {
                            ReferencepointId = 44,
                            Category = 2,
                            RSSI1 = 135,
                            RSSI2 = -9,
                            RSSI3 = 63,
                            X = 4,
                            Y = 4
                        },
                        new
                        {
                            ReferencepointId = 45,
                            Category = 3,
                            RSSI1 = 147,
                            RSSI2 = -21,
                            RSSI3 = 75,
                            X = 4,
                            Y = 5
                        },
                        new
                        {
                            ReferencepointId = 46,
                            Category = 1,
                            RSSI1 = 159,
                            RSSI2 = -33,
                            RSSI3 = 87,
                            X = 4,
                            Y = 6
                        },
                        new
                        {
                            ReferencepointId = 47,
                            Category = 6,
                            RSSI1 = 171,
                            RSSI2 = -45,
                            RSSI3 = 99,
                            X = 4,
                            Y = 7
                        },
                        new
                        {
                            ReferencepointId = 48,
                            Category = 3,
                            RSSI1 = 183,
                            RSSI2 = -57,
                            RSSI3 = 111,
                            X = 4,
                            Y = 8
                        },
                        new
                        {
                            ReferencepointId = 49,
                            Category = 9,
                            RSSI1 = 195,
                            RSSI2 = -69,
                            RSSI3 = 123,
                            X = 4,
                            Y = 9
                        },
                        new
                        {
                            ReferencepointId = 51,
                            Category = 3,
                            RSSI1 = 111,
                            RSSI2 = 15,
                            RSSI3 = 15,
                            X = 5,
                            Y = 1
                        },
                        new
                        {
                            ReferencepointId = 52,
                            Category = 6,
                            RSSI1 = 123,
                            RSSI2 = 3,
                            RSSI3 = 27,
                            X = 5,
                            Y = 2
                        },
                        new
                        {
                            ReferencepointId = 53,
                            Category = 7,
                            RSSI1 = 135,
                            RSSI2 = -9,
                            RSSI3 = 39,
                            X = 5,
                            Y = 3
                        },
                        new
                        {
                            ReferencepointId = 54,
                            Category = 5,
                            RSSI1 = 147,
                            RSSI2 = -21,
                            RSSI3 = 51,
                            X = 5,
                            Y = 4
                        },
                        new
                        {
                            ReferencepointId = 55,
                            Category = 6,
                            RSSI1 = 159,
                            RSSI2 = -33,
                            RSSI3 = 63,
                            X = 5,
                            Y = 5
                        },
                        new
                        {
                            ReferencepointId = 56,
                            Category = 2,
                            RSSI1 = 171,
                            RSSI2 = -45,
                            RSSI3 = 75,
                            X = 5,
                            Y = 6
                        },
                        new
                        {
                            ReferencepointId = 57,
                            Category = 1,
                            RSSI1 = 183,
                            RSSI2 = -57,
                            RSSI3 = 87,
                            X = 5,
                            Y = 7
                        },
                        new
                        {
                            ReferencepointId = 58,
                            Category = 4,
                            RSSI1 = 195,
                            RSSI2 = -69,
                            RSSI3 = 99,
                            X = 5,
                            Y = 8
                        },
                        new
                        {
                            ReferencepointId = 59,
                            Category = 8,
                            RSSI1 = 207,
                            RSSI2 = -81,
                            RSSI3 = 111,
                            X = 5,
                            Y = 9
                        },
                        new
                        {
                            ReferencepointId = 61,
                            Category = 7,
                            RSSI1 = 123,
                            RSSI2 = 3,
                            RSSI3 = 3,
                            X = 6,
                            Y = 1
                        },
                        new
                        {
                            ReferencepointId = 62,
                            Category = 2,
                            RSSI1 = 135,
                            RSSI2 = -9,
                            RSSI3 = 15,
                            X = 6,
                            Y = 2
                        },
                        new
                        {
                            ReferencepointId = 63,
                            Category = 1,
                            RSSI1 = 147,
                            RSSI2 = -21,
                            RSSI3 = 27,
                            X = 6,
                            Y = 3
                        },
                        new
                        {
                            ReferencepointId = 64,
                            Category = 5,
                            RSSI1 = 159,
                            RSSI2 = -33,
                            RSSI3 = 39,
                            X = 6,
                            Y = 4
                        },
                        new
                        {
                            ReferencepointId = 65,
                            Category = 1,
                            RSSI1 = 171,
                            RSSI2 = -45,
                            RSSI3 = 51,
                            X = 6,
                            Y = 5
                        },
                        new
                        {
                            ReferencepointId = 66,
                            Category = 5,
                            RSSI1 = 183,
                            RSSI2 = -57,
                            RSSI3 = 63,
                            X = 6,
                            Y = 6
                        },
                        new
                        {
                            ReferencepointId = 67,
                            Category = 1,
                            RSSI1 = 195,
                            RSSI2 = -69,
                            RSSI3 = 75,
                            X = 6,
                            Y = 7
                        },
                        new
                        {
                            ReferencepointId = 68,
                            Category = 4,
                            RSSI1 = 207,
                            RSSI2 = -81,
                            RSSI3 = 87,
                            X = 6,
                            Y = 8
                        },
                        new
                        {
                            ReferencepointId = 69,
                            Category = 9,
                            RSSI1 = 219,
                            RSSI2 = -93,
                            RSSI3 = 99,
                            X = 6,
                            Y = 9
                        },
                        new
                        {
                            ReferencepointId = 71,
                            Category = 2,
                            RSSI1 = 135,
                            RSSI2 = -9,
                            RSSI3 = -9,
                            X = 7,
                            Y = 1
                        },
                        new
                        {
                            ReferencepointId = 72,
                            Category = 3,
                            RSSI1 = 147,
                            RSSI2 = -21,
                            RSSI3 = 3,
                            X = 7,
                            Y = 2
                        },
                        new
                        {
                            ReferencepointId = 73,
                            Category = 4,
                            RSSI1 = 159,
                            RSSI2 = -33,
                            RSSI3 = 15,
                            X = 7,
                            Y = 3
                        },
                        new
                        {
                            ReferencepointId = 74,
                            Category = 4,
                            RSSI1 = 171,
                            RSSI2 = -45,
                            RSSI3 = 27,
                            X = 7,
                            Y = 4
                        },
                        new
                        {
                            ReferencepointId = 75,
                            Category = 5,
                            RSSI1 = 183,
                            RSSI2 = -57,
                            RSSI3 = 39,
                            X = 7,
                            Y = 5
                        },
                        new
                        {
                            ReferencepointId = 76,
                            Category = 7,
                            RSSI1 = 195,
                            RSSI2 = -69,
                            RSSI3 = 51,
                            X = 7,
                            Y = 6
                        },
                        new
                        {
                            ReferencepointId = 77,
                            Category = 1,
                            RSSI1 = 207,
                            RSSI2 = -81,
                            RSSI3 = 63,
                            X = 7,
                            Y = 7
                        },
                        new
                        {
                            ReferencepointId = 78,
                            Category = 4,
                            RSSI1 = 219,
                            RSSI2 = -93,
                            RSSI3 = 75,
                            X = 7,
                            Y = 8
                        },
                        new
                        {
                            ReferencepointId = 79,
                            Category = 7,
                            RSSI1 = 231,
                            RSSI2 = -105,
                            RSSI3 = 87,
                            X = 7,
                            Y = 9
                        },
                        new
                        {
                            ReferencepointId = 81,
                            Category = 9,
                            RSSI1 = 147,
                            RSSI2 = -21,
                            RSSI3 = -21,
                            X = 8,
                            Y = 1
                        },
                        new
                        {
                            ReferencepointId = 82,
                            Category = 5,
                            RSSI1 = 159,
                            RSSI2 = -33,
                            RSSI3 = -9,
                            X = 8,
                            Y = 2
                        },
                        new
                        {
                            ReferencepointId = 83,
                            Category = 5,
                            RSSI1 = 171,
                            RSSI2 = -45,
                            RSSI3 = 3,
                            X = 8,
                            Y = 3
                        },
                        new
                        {
                            ReferencepointId = 84,
                            Category = 8,
                            RSSI1 = 183,
                            RSSI2 = -57,
                            RSSI3 = 15,
                            X = 8,
                            Y = 4
                        },
                        new
                        {
                            ReferencepointId = 85,
                            Category = 6,
                            RSSI1 = 195,
                            RSSI2 = -69,
                            RSSI3 = 27,
                            X = 8,
                            Y = 5
                        },
                        new
                        {
                            ReferencepointId = 86,
                            Category = 6,
                            RSSI1 = 207,
                            RSSI2 = -81,
                            RSSI3 = 39,
                            X = 8,
                            Y = 6
                        },
                        new
                        {
                            ReferencepointId = 87,
                            Category = 7,
                            RSSI1 = 219,
                            RSSI2 = -93,
                            RSSI3 = 51,
                            X = 8,
                            Y = 7
                        },
                        new
                        {
                            ReferencepointId = 88,
                            Category = 2,
                            RSSI1 = 231,
                            RSSI2 = -105,
                            RSSI3 = 63,
                            X = 8,
                            Y = 8
                        },
                        new
                        {
                            ReferencepointId = 89,
                            Category = 8,
                            RSSI1 = 243,
                            RSSI2 = -117,
                            RSSI3 = 75,
                            X = 8,
                            Y = 9
                        },
                        new
                        {
                            ReferencepointId = 91,
                            Category = 8,
                            RSSI1 = 159,
                            RSSI2 = -33,
                            RSSI3 = -33,
                            X = 9,
                            Y = 1
                        },
                        new
                        {
                            ReferencepointId = 92,
                            Category = 4,
                            RSSI1 = 171,
                            RSSI2 = -45,
                            RSSI3 = -21,
                            X = 9,
                            Y = 2
                        },
                        new
                        {
                            ReferencepointId = 93,
                            Category = 5,
                            RSSI1 = 183,
                            RSSI2 = -57,
                            RSSI3 = -9,
                            X = 9,
                            Y = 3
                        },
                        new
                        {
                            ReferencepointId = 94,
                            Category = 8,
                            RSSI1 = 195,
                            RSSI2 = -69,
                            RSSI3 = 3,
                            X = 9,
                            Y = 4
                        },
                        new
                        {
                            ReferencepointId = 95,
                            Category = 4,
                            RSSI1 = 207,
                            RSSI2 = -81,
                            RSSI3 = 15,
                            X = 9,
                            Y = 5
                        },
                        new
                        {
                            ReferencepointId = 96,
                            Category = 9,
                            RSSI1 = 219,
                            RSSI2 = -93,
                            RSSI3 = 27,
                            X = 9,
                            Y = 6
                        },
                        new
                        {
                            ReferencepointId = 97,
                            Category = 4,
                            RSSI1 = 231,
                            RSSI2 = -105,
                            RSSI3 = 39,
                            X = 9,
                            Y = 7
                        },
                        new
                        {
                            ReferencepointId = 98,
                            Category = 1,
                            RSSI1 = 243,
                            RSSI2 = -117,
                            RSSI3 = 51,
                            X = 9,
                            Y = 8
                        },
                        new
                        {
                            ReferencepointId = 99,
                            Category = 7,
                            RSSI1 = 255,
                            RSSI2 = -129,
                            RSSI3 = 63,
                            X = 9,
                            Y = 9
                        });
                });

            modelBuilder.Entity("dpu_server.Models.Heatmap", b =>
                {
                    b.HasOne("dpu_server.Models.Referencepoint", "Referencepoint")
                        .WithMany()
                        .HasForeignKey("ReferencepointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dpu_server.Models.Referencepoint", null)
                        .WithOne("Heatmap")
                        .HasForeignKey("dpu_server.Models.Heatmap", "ReferencepointId1");
                });
#pragma warning restore 612, 618
        }
    }
}
